# ------------------------------------
# Picamera3 Actor
# ------------------------------------
["picamera3.hi_res_size"]
width = 2304
height = 1296

["picamera3.lo_res_size"]
width = 320
height = 320

# ------------------------------------
# Yolo11 Ncnn Actor
# ------------------------------------
["yolo11ncnn"]
proto_path = "/home/steve/ai-trap-cpp/resources/model.ncnn.param"
model_path = "/home/steve/ai-trap-cpp/resources/model.ncnn.bin"



