# ------------------------------------
# Picamera3 Actor
# ------------------------------------
["picamera3"]

["picamera3.hi_res_size"]
width = 4096
height = 2048

["picamera3.lo_res_size"]
width = 320
height = 320

# ------------------------------------
# Yolo11 Ncnn Actor
# ------------------------------------
["yolo11ncnn"]
proto_path = ""
model_path = ""



